### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PrValentin** [The-West-Scripts/tw-perseus-toolkit#3]
Hello guys,

When i have 2 windows with works opened or more, the button make 8 action from first job and 1 (the last) from second job. Or if I have more than 2, the button mix all jobs. Can you make the button to don't mix the jobs if I have more than 2 windows open?

Thanks in advance!

**Comment by mr-perseus** [comment]
Thanks for reporting. I will have a look and fix it within the next few weeks.
